provider: 'AWS'
# optionally specify Region for your AMI
# FOG gem defaults AWS to 'us-east-1'
# region: 'us-west-2'

aws_access_key_id: 'YOUR_SECRET_ACCESS_KEY_ID'
aws_secret_access_key: 'YOUR_SECRET_ACCESS_KEY'
# specify another config file for your aws credentials
# in case you want to keep them encrypted. This file
# will take precedence if access keys are defined in both
# files
# aws_credential_file: '~/YOUR_AWS_CREDENTIAL_FILE'

ami_id: 'SOME-AMI'
flavor_id: 'm1.large'

key_name: 'some-key-pair'
private_key_path: "~/.ssh/some-private-key.pem"
